version: '2'
services:
  shopfront:
    image: prasantk/djshopfront
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  
  productcatalogue:
    image: prasantk/djproductcatalogue
    ports:
     - "8020:8020"
  
  stockmanager:
    image: prasantk/djstockmanager
    ports:
     - "8030:8030"
